version: 1.0.{build}
image: Visual Studio 2017
environment:
  _SkipNearestTargetFrameworkResolution: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    cd Dozens.Core.Test

    dotnet test


    cd ..\Dozens.Test\bin\Debug

    vstest.console /logger:Appveyor Dozens.Test.dll